/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpotsyncRouteImport } from './routes/spotsync'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MusicRouteImport } from './routes/music'
import { Route as MeetingsRouteImport } from './routes/meetings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DriveRouteImport } from './routes/drive'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as IndexRouteImport } from './routes/index'

const SpotsyncRoute = SpotsyncRouteImport.update({
  id: '/spotsync',
  path: '/spotsync',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicRoute = MusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsRoute = MeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DriveRoute = DriveRouteImport.update({
  id: '/drive',
  path: '/drive',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacts': typeof ContactsRoute
  '/drive': typeof DriveRoute
  '/login': typeof LoginRoute
  '/meetings': typeof MeetingsRoute
  '/music': typeof MusicRoute
  '/news': typeof NewsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/spotsync': typeof SpotsyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacts': typeof ContactsRoute
  '/drive': typeof DriveRoute
  '/login': typeof LoginRoute
  '/meetings': typeof MeetingsRoute
  '/music': typeof MusicRoute
  '/news': typeof NewsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/spotsync': typeof SpotsyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacts': typeof ContactsRoute
  '/drive': typeof DriveRoute
  '/login': typeof LoginRoute
  '/meetings': typeof MeetingsRoute
  '/music': typeof MusicRoute
  '/news': typeof NewsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/spotsync': typeof SpotsyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacts'
    | '/drive'
    | '/login'
    | '/meetings'
    | '/music'
    | '/news'
    | '/profile'
    | '/register'
    | '/spotsync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacts'
    | '/drive'
    | '/login'
    | '/meetings'
    | '/music'
    | '/news'
    | '/profile'
    | '/register'
    | '/spotsync'
  id:
    | '__root__'
    | '/'
    | '/contacts'
    | '/drive'
    | '/login'
    | '/meetings'
    | '/music'
    | '/news'
    | '/profile'
    | '/register'
    | '/spotsync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactsRoute: typeof ContactsRoute
  DriveRoute: typeof DriveRoute
  LoginRoute: typeof LoginRoute
  MeetingsRoute: typeof MeetingsRoute
  MusicRoute: typeof MusicRoute
  NewsRoute: typeof NewsRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  SpotsyncRoute: typeof SpotsyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spotsync': {
      id: '/spotsync'
      path: '/spotsync'
      fullPath: '/spotsync'
      preLoaderRoute: typeof SpotsyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music': {
      id: '/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof MusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings': {
      id: '/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof MeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drive': {
      id: '/drive'
      path: '/drive'
      fullPath: '/drive'
      preLoaderRoute: typeof DriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactsRoute: ContactsRoute,
  DriveRoute: DriveRoute,
  LoginRoute: LoginRoute,
  MeetingsRoute: MeetingsRoute,
  MusicRoute: MusicRoute,
  NewsRoute: NewsRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  SpotsyncRoute: SpotsyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
